id: A4BFF3B9B
title: 'Drop of Wisdom Nectar: A Guru Yoga'
type: translation
pechas:
- I36B99DC4
- IE47CE7CB
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:12:10.317871
  last_modified_at: 2023-01-04 12:12:10.317883
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I36B99DC4/BA1D: D9A5
  IE47CE7CB/821D: D9A5
